### ISSUE TITLE
undefined method `set_default' for main:Object

### ISSUE THREAD

**Issue by vicvega** [moll/mina-rsync#17]
With `mina` `v1.0.0` the following error occurs

```
mina aborted!
NoMethodError: undefined method `set_default' for main:Object
```

It works well with older mina version, but `v1.0.0` introduced breaking changes

See also https://github.com/mina-deploy/mina/issues/420

**Comment by pedroresende** [comment]
I'm also getting this error...

**Comment by acurley** [comment]
This is addressed in my pull request #16.  Feel free to fork until it is merged.
